@Api.Ordenes_HostAddress = http://localhost:5241

GET {{Api.Ordenes_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Api.Ordenes_HostAddress}}/api/productos
Content-Type: application/json

{
    "nombre": "Laptop Dell",
    "cantidad": 10
}
